/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2020 Jean Gressmann <jean@0x42.de>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 */


import "oaidl.idl";
import "ocidl.idl";

[
	uuid(fd71338b-9533-4785-8c2f-664ece4bebee),
	version(1.0),
	helpstring("SuperCAN 1.0 Type Library"),
]
library SuperCAN
{
	importlib("stdole2.tlb");

	struct SuperCANRingBufferMapping
	{
		BSTR MemoryName;
		BSTR EventName;
		unsigned long Elements;
		unsigned long Bytes;
	};

	struct SuperCANBitTimingParams
	{
		unsigned short brp;
		unsigned short tseg1;
		byte tseg2;
		byte sjw;
	};

	struct SuperCANDeviceData
	{
		BSTR name;
		struct SuperCANBitTimingParams nm_min, nm_max, dt_min, dt_max;
		unsigned long can_clock_hz;
		unsigned short feat_perm;
		unsigned short feat_conf;
		byte fw_ver_major;
		byte fw_ver_minor;
		byte fw_ver_patch;
		byte sn_bytes[16];
		byte sn_length;
	};

	[
		object,
		uuid(434A1140-50D8-4C49-AB8F-9FD1A7327CE0),
		pointer_default(unique),
		oleautomation,
	]
	interface ISuperCANDevice : IUnknown
	{
		HRESULT HasConfigurationAccess([out,retval] boolean* config_access);
		HRESULT GetRingBufferMappings(
			[out] struct SuperCANRingBufferMapping* rx, 
			[out] struct SuperCANRingBufferMapping* tx);
		HRESULT GetDeviceData([out] struct SuperCANDeviceData* data);
		
		HRESULT SetBus([in] boolean on);
		HRESULT SetFeatureFlags([in] unsigned long flags);
		HRESULT SetNominalBitTiming([in] struct SuperCANBitTimingParams param);
		HRESULT SetDataBitTiming([in] struct SuperCANBitTimingParams param);		
	};


	[
		object, // The [object] interface attribute identifies a COM interface. else DCE RPC
		uuid(8F8C4375-2DFE-4335-8947-036F965BD927),
		pointer_default(unique),
		oleautomation, // either this or 'dual' are required for COM
	]
	interface ISuperCAN : IUnknown
	{
		HRESULT DeviceScan([out] unsigned long* count);
		HRESULT DeviceGetCount([out] unsigned long* count);
		HRESULT DeviceOpen(
			[in] unsigned long index, 
			[in] boolean request_config_access,
			[out] ISuperCANDevice** dev);
	};


	[
		uuid(E6214AB1-56AD-4215-8688-095D3816F260),
		helpstring("SuperCAN class"),
	]
	coclass CSuperCAN
	{
		[default] interface ISuperCAN;
	};
};
